config/routes.rb
SampleApp::Application.routes.draw do
  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  get "users/new"

  match '/listeNonSportif', :to => 'users#listeNonSportif'
  match '/listePdf', :to => 'users#listePdf'
  match '/listeUser', :to => 'users#listeUserCV'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => 'pages#home'

end

app/models/PdfDocument.rb
class PdfDocument < Prawn::Document
  def to_pdf
    text "Article ", :size => 30, :style => :bold
    move_down(30)
    text "aguibou"
    move_down(10)

    render
  end
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :nom, :date, :poids_actu, :poids_ideal, :taille,
                  :email, :faire_sport, :aimer_faire_sport, :password, :password_confirmation, :attach

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  taille_regex = /\A[123](\.\d{1,2})?\z/
  poids_regex = /\A\d{2,3}(\.\d{1,2})?\z/
  
  validates :nom, :presence => true, :length   => { :maximum => 50 }
  validates :email, :presence => true, :format => { :with => email_regex }, :uniqueness => { :case_sensitive => false }

  validates :taille, :presence => true, :format => { :with => taille_regex }
  validates :poids_actu, :presence => true, :format => { :with => poids_regex }
  validates :poids_ideal, :presence => true, :format => { :with => poids_regex }, :numericality => {:less_than=> :poids_actu}

  validates :password, :presence => true, :confirmation => true, :length => { :within => 6..40 }

  has_attached_file :attach, :presence => true
  #validates_attachment_content_type :attach, :content_type => ["application/pdf"]  
                   
  before_save :encrypt_password

  def faitSport
    if faire_sport == "1"
      return "oui"
    else
      return "non"
    end
  end

  def aimeraiFaireSport
    if aimer_faire_sport == "1"
      return "oui"
    else
      return "non"
    end
  end
 
    # methode de calcul de l'IMC
  def calc_imc
      return (poids_actu / (taille*taille)).to_s()
  end

    #Methode de calcul de l'age
  def age
     if Date.today.year - date.year > 1
        return (Date.today.year - date.year).to_s() +" ans"
     elsif Date.today.year - date.year == 1
        return 1.to_s() +"an"
     elsif Date.today.month - date.month >= 1
        return (Date.today.month - date.month).to-s() + " mois"
     else
        return (Date.today.day - date.day).to_s() + " jours"
     end
  end

  def has_password?(password_soumis)
    encrypted_password == encrypt(password_soumis)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end


# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  nom                :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
# encoding: utf-8
class PagesController < ApplicationController

  def home
    @titre = "Accueil"
  end

  def contact
    @titre = "Contact"
  end

  def about
    @titre = "À Propos"
  end

  def help
    @title = "Aide"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @titre = "S'identifier"
  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Combinaison Email/Mot de passe invalide."
      @titre = "S'identifier"
      render 'new'
    else
      sign_in user
      redirect_to user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @titre = @user.nom
  end

  def listePdf
   @titre = "Liste des utilisateurs en pdf"
   @liste = User.find(:all)
    
    pdf_content = PdfDocument.new.to_pdf

    respond_to do |format|
      format.pdf do
        send_data pdf_content, filename: "liste.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  def listeUserCV
    @titre = "Liste des utilisateurs"
    @liste = User.find(:all)
  end

  def listeNonSportif
    @titre = "Liste des utilisateurs non sportifs"
    @liste = User.where({faire_sport: '0'} && {aimer_faire_sport: '1'})
  end

  def new
    @user = User.new	
    @titre = "Inscription"
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Bienvenue dans l'Application Exemple !"
      redirect_to @user
    else
      @titre = "Sign up"
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Retourner un titre basé sur la page.
  def titre
    base_titre = "Simple App du Tutoriel Ruby on Rails"
    if @titre.nil?
      base_titre
    else
      "#{base_titre} | #{@titre}"
    end
  end

  def logo
    image_tag("logo.png", :alt => "Application Exemple", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    #self.current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    #self.current_user = nil
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "À Propos", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Accueil", root_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Profil", current_user %></li>
      <% end %>
      <li><%= link_to "Aide", help_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Déconnexion", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "S'identifier", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= titre %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>

      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>

app/views/layouts/pdf.html.haml
%html
  %head
    %meta{ "http-equiv" => "content-type", content: "text/html; charset=utf-8" }
  %body
       Bonjour
      = yield 

app/views/pages/about.html.erb
<h1>À Propos de nous</h1>
  <p>
      <a href="http://railstutorial.org/">Le Tutoriel Ruby on Rails</a>
      est un projet de livre et de screencasts pour apprendre le développement web
      avec <a href="http://rubyonrails.org/">Ruby on Rails</a>. Ceci
      est l'Application Exemple du tutoriel.
  </p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Aide</h1>
<p>
  Obtenez de l'aide sur le Tutoriel Ruby on Rails Tutorial sur la
  <a href="http://railstutorial.org/help">page d'aide du Tutoriel Rails</a>.
  Pour obtenir de l'aide sur cette application exemple, consultez le
  <a href="http://railstutorial.org/book">livre du Tutoriel Rails</a>.
</p>

app/views/pages/home.html.erb
<h1>Simple App</h1>
  <p>
      Ceci est la page d'accueil de l'Application Exemple du
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>.
</p>
<%= link_to "S'inscrire !", signup_path, :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "erreur") %> 
        ont empêché d'enregistrer votre inscription</h2>
    <p>Merci de corriger ces champs :</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/listeNonSportif.html.erb
<h1>Liste des utilisateurs non sportifs désirant faire du sport</h1>
<table class="profile" summary="Information profil">
  <tr>
    <td>
         <strong>Nom </strong>
    </td>
    <td>
         <strong>E-mail </strong>
    </td>
    <td>
         <strong>CV </strong>
    </td>
  </tr>
  
  <% @liste.each do |l| %>
   <tr>
      <td> <%= l.nom %> </td>
      <td> <%= l.email %> </td>
      <td> <%= link_to 'print', l.attach.url %> </td>  
   </tr>  
  <% end %>
</table>

app/views/users/listeUserCV.html.erb
<div>
    <h1>Liste des utilisateurs et leurs CV </h1>

   <div>
      <%= link_to "pdf" , listePdf_path %> 
   </div>
</div>

<table class="profile" summary="Information profil">
  <tr>
    <td>
         <strong>Nom </strong>
    </td>
    <td>
         <strong>E-mail </strong>
    </td>
    <td>
         <strong>CV </strong>
    </td>
  </tr>
  
  <% @liste.each do |l| %>
   <tr>
      <td> <%= l.nom %> </td>
      <td> <%= l.email %> </td>
      <td> <%= link_to 'print', l.attach.url %> </td>  
   </tr>  
  <% end %>
</table>

app/views/users/liste_non_sportif.html.erb
<h1>Liste des utilisateurs non sportifs désirant faire du sport</h1>
<table class="profile" summary="Information profil">
  <tr>
    <td>
         <strong>Nom </strong>
    </td>
    <td>
         <strong>E-mail </strong>
    </td>
    <td>
         <strong>CV </strong>
    </td>
  </tr>
  
  <% @liste.each do |l| %>
   <tr>
      <td> <%= l.nom %> </td>
      <td> <%= l.email %> </td>
      <td> <%= link_to 'print', l.attach.url %> </td>  
   </tr>  
  <% end %>
</table>

app/views/users/listecv.html.erb
<h1>Liste des CV de tous les utilisateurs</h1>
<ul class="users">
  <% @liste.each do |l| %>
    <li>
       <%= l.nom %> <%= link_to 'cv', l.cv.url %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Inscription</h1>

<%= form_for(@user, :html =>{:multipart => true}) do |f| %>
   <%= render 'shared/error_messages', :object=>f.object %> 
 <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
 
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :"Date de Naissance" %><br />
    <%= f.date_select :date, :start_year=>1985, :use_month_numbers=>true, :order=>[:day, :month, :year]%>
  </div>

  <div class="field">
    <%= f.label :"Poids actuel" %><br />
    <%= f.text_field :poids_actu, type: "number" %>
  </div>

  <div class="field">
    <%= f.label :"Poids idéal" %><br />
    <%= f.text_field :poids_ideal, type: "number" %>
  </div>
  
  <div class="field">
    <%= f.label :taille %><br />
    <%= f.text_field :taille %>
  </div>
  
  <div class="field">
      <%= f.check_box :faire_sport, :valeur_on=>1, :valeur_off=>0 %>
      <%= f.label :"faites-vous du sport actuellement?" %>
  </div>

  <div class="field">
      <%= f.check_box :aimer_faire_sport, :valeur_on=>1, :valeur_off=>0 %>
      <%= f.label :"aimeriez-vous faire du sport?" %>
  </div>

  <div class="field">
    <%= f.label :attach, "Joindre le CV " %>
    <%= f.file_field :attach %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "Inscription" %>
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Information profil">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.nom %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Age : </strong> <%= @user.age %><br />
      <strong>Poids actuel : </strong> <%= @user.poids_actu %><br />
      <strong>Poids idéal : </strong> <%= @user.poids_ideal %><br />
      <strong>IMC  : </strong> <%= @user.calc_imc %><br />
      <strong>Fait du sport : </strong> <%= @user.faitSport %><br />
      <strong>Aimerai faire du sport : </strong> <%= @user.aimeraiFaireSport ;%><br />
      <%= link_to "Afficher CV " , @user.attach.url %> 
    </td>
  </tr>
</table>

<div>
      <%= link_to "Liste des utilisateurs et leurs CV " , listeUser_path %> 
</div>

<div>
      <%= link_to "Liste des gens non sportifs désirant le faire " , listeNonSportif_path %> 
</div>

app/views/users/show_pdf.pdf.erb
<h1>Liste des utilisateurs et leurs CV </h1>

<table class="profile" summary="Information profil">
  <tr>
    <td>
         <strong>Nom </strong>
    </td>
    <td>
         <strong>E-mail </strong>
    </td>
    <td>
         <strong>CV </strong>
    </td>
  </tr>
  
  <% @liste.each do |l| %>
   <tr>
      <td> <%= l.nom %> </td>
      <td> <%= l.email %> </td>
      <td> <%= link_to 'print', l.attach.url %> </td>  
   </tr>  
  <% end %>
</table>